<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title> Error Handling </title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="../../Assets/stylesPages.css">
    <script src="../../Assets/scriptPages.js"></script>
  </head>
  <body>
    <h1> Error Handling (ver 4.0.0) </h1>
    <p> Updated: ( 2017-12-12 / 2018-04-14 / 2019-02-08 / 2020-07-24 / 2025-03-01 )</p>
    <nav class="sitenav">
      <a href="../../index.html">MySite > </a>
      <a href="../index.html">JavaScript > </a> Error Handling
    </nav>
    <table class="table">
      <caption>
        Error Object
        <span class="changeListOrder">[Ordered: <span>Alphabetically</span>]</span>
      </caption>
      <tr>
        <th style="width:30%;"> Methods / Properties</th>
        <th> Description </th>
      </tr>
      <tr class="10.01">
        <td> new Error(<i>msg:str</i>) </td>
        <td>
          - creates an error object (thrown when Runtime error occurs)
          <span id="browserSupport" updated="2020-07-24">
            <span><i class="fab fa-chrome"></i> 1 </span>
            <span><i class="fab fa-firefox"></i> 1 </span>
            <span><i class="fab fa-opera"></i> 4 </span>
            <span><i class="fab fa-internet-explorer"></i><i class="fab fa-edge"></i> 6 </span>
            <span><i class="fab fa-safari"></i> 1 </span>
            <span><i class="fab fa-node-js"></i> 0.1.100 </span>
          </span>
        </td>
      </tr>
      <tr class="20.01">
        <td> new EvalError(<i>msg:str</i>) </td>
        <td>
          - creates a evalError object <u>(doesn't thrown by JS it is remained for compatibility only!) </u>
          <span id="browserSupport" updated="2020-07-24">
            <span><i class="fab fa-chrome"></i> 1 </span>
            <span><i class="fab fa-firefox"></i> 1 </span>
            <span><i class="fab fa-opera"></i> 4 </span>
            <span><i class="fab fa-internet-explorer"></i><i class="fab fa-edge"></i> 6 </span>
            <span><i class="fab fa-safari"></i> 1 </span>
            <span><i class="fab fa-node-js"></i> 0.1.100 </span>
          </span>
        </td>
      </tr>
      <tr class='15.02'>
        <td> new RangeError(<i>msg:str</i>) </td>
        <td>
          - creates a rangeError object (thrown when a number is outside of legal limits)
          <span id="browserSupport" updated="2020-07-24">
            <span><i class="fab fa-chrome"></i> 1 </span>
            <span><i class="fab fa-firefox"></i> 1 </span>
            <span><i class="fab fa-opera"></i> 4 </span>
            <span><i class="fab fa-internet-explorer"></i><i class="fab fa-edge"></i> 6 </span>
            <span><i class="fab fa-safari"></i> 1 </span>
            <span><i class="fab fa-node-js"></i> 0.1.100 </span>
          </span>
        </td>
      </tr>
      <tr class='15.01'>
        <td> new ReferenceError(<i>msg:str</i>) </td>
        <td>
          - creates a referenceError object (thrown when a non-existing variable is referenced)
          <span id="browserSupport" updated="2020-07-24">
            <span><i class="fab fa-chrome"></i> 1 </span>
            <span><i class="fab fa-firefox"></i> 1 </span>
            <span><i class="fab fa-opera"></i> 4 </span>
            <span><i class="fab fa-internet-explorer"></i><i class="fab fa-edge"></i> 6 </span>
            <span><i class="fab fa-safari"></i> 1 </span>
            <span><i class="fab fa-node-js"></i> 0.1.100 </span>
          </span>
        </td>
      </tr>
      <tr class="05.01">
        <td> new SyntaxError(<i>msg:str</i>) </td>
        <td>
          - creates a syntaxError object (thrown when the code is syntactically invalid)
          <span id="browserSupport" updated="2020-07-24">
            <span><i class="fab fa-chrome"></i> 1 </span>
            <span><i class="fab fa-firefox"></i> 1 </span>
            <span><i class="fab fa-opera"></i> 4 </span>
            <span><i class="fab fa-internet-explorer"></i><i class="fab fa-edge"></i> 6 </span>
            <span><i class="fab fa-safari"></i> 1 </span>
            <span><i class="fab fa-node-js"></i> 0.1.100 </span>
          </span>
        </td>
      </tr>
      <tr class='15.02'>
        <td> new TypeError(<i>msg:str</i>) </td>
        <td>
          - creates a typeError object (thrown when the value is an unexpected type (like a property is not on the object's prototype chain))
          <span id="browserSupport" updated="2020-07-24">
            <span><i class="fab fa-chrome"></i> 1 </span>
            <span><i class="fab fa-firefox"></i> 1 </span>
            <span><i class="fab fa-opera"></i> 4 </span>
            <span><i class="fab fa-internet-explorer"></i><i class="fab fa-edge"></i> 6 </span>
            <span><i class="fab fa-safari"></i> 1 </span>
            <span><i class="fab fa-node-js"></i> 0.1.100 </span>
          </span>
        </td>
      </tr>
      <tr class='15.03'>
        <td> new URIError(<i>msg:str</i>) </td>
        <td>
          - creates a URIError object (thrown when an illegal character is used in a URI function (like <mark>decodeURI()</mark>, ect...))
          <span id="browserSupport" updated="2020-07-24">
            <span><i class="fab fa-chrome"></i> 1 </span>
            <span><i class="fab fa-firefox"></i> 1 </span>
            <span><i class="fab fa-opera"></i> 4 </span>
            <span><i class="fab fa-internet-explorer"></i><i class="fab fa-edge"></i> 6 </span>
            <span><i class="fab fa-safari"></i> 1 </span>
            <span><i class="fab fa-node-js"></i> 0.1.100 </span>
          </span>
        </td>
      </tr>
      <tr class="25.01">
        <td colspan="2"> Properties </td>
      </tr>
      <tr class="25.03">
        <td> <strong>errorObj</strong>.message </td>
        <td>
          - returns the error's message as a string
          <span id="browserSupport" updated="2020-07-24">
            <span><i class="fab fa-chrome"></i> 1 </span>
            <span><i class="fab fa-firefox"></i> 1 </span>
            <span><i class="fab fa-opera"></i> 4 </span>
            <span><i class="fab fa-internet-explorer"></i><i class="fab fa-edge"></i> 6 </span>
            <span><i class="fab fa-safari"></i> 1 </span>
            <span><i class="fab fa-node-js"></i> 0.1.100 </span>
          </span>
        </td>
      </tr>
      <tr class="25.02">
        <td> <strong>errorObj</strong>.name </td>
        <td>
          - returns the error object constructor's name as a string
          <span id="browserSupport" updated="2020-07-24">
            <span><i class="fab fa-chrome"></i> 1 </span>
            <span><i class="fab fa-firefox"></i> 1 </span>
            <span><i class="fab fa-opera"></i> 4 </span>
            <span><i class="fab fa-internet-explorer"></i><i class="fab fa-edge"></i> 6 </span>
            <span><i class="fab fa-safari"></i> 1 </span>
            <span><i class="fab fa-node-js"></i> 0.1.100 </span>
          </span>
        </td>
      </tr>
    </table>
    <h2 style="color:green;"><u> Notes : </u></h2>
    <details class="example" id="notes">
      <summary> Notes :</summary>
      <p> - not standart <mark>profile()</mark> and <mark>profileEnd()</mark> not tested [2019-02-09], it does some perfornace profile thing </p>
    </details>
    <h2 style="color:green;"><u> Useful Links : </u></h2>
    <p><a href="https://www.w3schools.com/js/js_errors.asp" target="_blank"> W3Schools JavaScript Errors </a></p>
    <h2 style="color:green;"><u> Remember This : </u></h2>
    <p> - using the <mark>with(){}</mark> statement is Not Recommended and restricted in "strict mode" </p>
    <p> - the <mark>try</mark> statement cannot handle SyntaxError (obviously) </p>
    <h2 style="color:green;"><u> Description and Demonstration : </u></h2>
    <p> - when JavaScript encounters and error it creates an apropriate Error Object and throws it and stops all further script execution </p>
    <hr>
    <!--------------------------------------------------------------------------------------------------------------------------------->
    <h2 style="color:darkblue;"><u> The Error objects <mark>Error</mark> / <mark>TypeError</mark> / <mark>ReferenceError</mark> / <mark>RangeError</mark> / <mark>SyntaxError</mark> / <mark>EvalError</mark> / <mark>URIError</mark> / <mark>name</mark> / <mark>message</mark> </u></h2>
    <p> - we can create custom Error objects and throw them with the <mark>throw</mark> statement </p>
    <details class="example">
      <summary> DEMO </summary>
      <pre>
    var error_ = new Error("myError");          // create a new error object
    var ref_error = ReferenceError("my_RefError");  // create a new referenceError object <b>("new" keyword can be omitted but not recommended)</b>
        
    ref_error.name                              // -> "ReferenceError"
    ref_error.message                           // -> "my_RefError"     // message passed as argument
    throw ref_error;                            // ReferenceError throw in the console with the message "my_RefError"
    
    var myDate = new Date();                    // <b>all further code is not executed because we have thrown an execption above</b>
    </pre>
      <p><b> - the <mark>RangeError</mark> is thrown when a number is outside of legal limits </b></p>
      <pre>
    var number = 14;
    
    try {                       
        number.toPrecision(500); 
    }
    catch(errorObject){
        errorObject.name                        // -> "RangeError"
        errorObject.message                     // -> "toPrecision() argument must be between 1 and 100"
    }
    </pre>
      <p><b> - the <mark>ReferenceError</mark> is thrown when a non-existing variable is referenced </b></p>
      <pre>
    try {
        cap;   
    }
    catch(errorObject){
        errorObject.name                        // -> "ReferenceError"
        errorObject.message                     // -> "cap is not defined"
    }
    </pre>
      <p><b> - the <mark>SyntaxError</mark> is thrown when the code is syntactically invalid </b></p>
      <pre>
    try{
        eval("console{}")                       // <u>we use eval function here, otherwise the "try" statement cannot pass the exeption</u>
        console.{}                              // this would shut down all further code because of the SyntaxError
    }
    catch(errorObject){
        errorObject.name                        // -> "SyntaxError"
        errorObject.message                     // -> "Invalid or unexpected token {"
    }
    </pre>
      <p><b> - the <mark>TypeError</mark> is thrown when the value is an unexpected type (like a property is not on the object's prototype chain) </b></p>
      <pre>
    var one = true;
    try{
        one.getDate(); 
    }
    catch(errorObject){
        errorObject.name                        // -> "TypeError"
        errorObject.message                     // -> "one.getDate is not a function"
    }
    </pre>
      <p><b> - the <mark>URIError</mark> is thrown when an illegal character is used in a URI function </b></p>
      <pre>
    try{
        decodeURI("%£$*&");          
    }
    catch(errorObject){
        errorObject.name                        // -> "URIError"
        errorObject.message                     // -> "URI malformed"
    }
    </pre>
      <p><b> - the <mark>EvalError</mark> does NOT throw any eval errors it remained in JavaScript for compatibility</b></p>
      <pre>
    try {
        eval(blaBla);                           <span style="color:orangered;">&lt;-- does not throw any EvalError</span>
    } catch(e) {
        e.name                                  // -> "ReferenceError"      // not an EvalError instance
    }
    </pre>
    </details>
    <details class="example">
      <summary> Example : </summary>
      <h4><u> Error Object names and messages </u></h4>
      <p id="errObj_prop-1"></p>
      <p id="errObj_prop-2"></p>
      <p id="errObj_prop-3"></p>
      <p id="errObj_prop-4"></p>
      <p id="errObj_prop-5"></p>
      <script>
    var nR = 12;
    
// --- RangeError
    try{
        nR.toFixed(500);
    }
    catch(error_1){
        document.getElementById('errObj_prop-1').innerHTML = 
            error_1 + "<br>" +
            error_1.name + "<br>" +
            error_1.message;
    }
// --- ReferenceError
    try{
        var thisVariable = "Kicsi " + mano;
    }
    catch(error_2){
        document.getElementById('errObj_prop-2').innerHTML = 
            error_2 + "<br>" +
            error_2.name + "<br>" +
            error_2.message;
    }
// --- SyntaxError
    var Xnr;
    try{
        eval("alert('message display)';");
    }
    catch(error_3){
        document.getElementById('errObj_prop-3').innerHTML =
            error_3 + "<br>" +
            error_3.name + "<br>" +
            error_3.message;
    }
// --- TypeError
    var Xstr = "thisText";
    try{
        Xstr.pop();
    }
    catch(error_4){
        document.getElementById('errObj_prop-4').innerHTML =
            error_4 + "<br>" +
            error_4.name + "<br>" +
            error_4.message;
    }
// --- URIError
    try{
        decodeURI("%£$*&");
    }
    catch(error_5){
        document.getElementById('errObj_prop-5').innerHTML =
            error_5 + "<br>" +
            error_5.name + "<br>" +
            error_5.message;
    }
</script>
      <details>
        <summary> CODE : </summary>
        <pre>
    &lt;p id="errObj_prop-1"&gt;&lt;/p&gt;
    &lt;p id="errObj_prop-2"&gt;&lt;/p&gt;
    &lt;p id="errObj_prop-3"&gt;&lt;/p&gt;
    &lt;p id="errObj_prop-4"&gt;&lt;/p&gt;
    &lt;p id="errObj_prop-5"&gt;&lt;/p&gt;
&lt;script>
    var nR = 12;
    
// --- RangeError
    try{
        nR.toFixed(500);
    }
    catch(error_1){
        document.getElementById('errObj_prop-1').innerHTML = 
            error_1 + "&lt;br&gt;" +
            error_1.name + "&lt;br&gt;" +
            error_1.message;
    }
// --- ReferenceError
    try{
        var thisVariable = "Kicsi " + mano;
    }
    catch(error_2){
        document.getElementById('errObj_prop-2').innerHTML = 
            error_2 + "&lt;br&gt;" +
            error_2.name + "&lt;br&gt;" +
            error_2.message;
    }
// --- SyntaxError
    var Xnr;
    try{
        eval("alert('message display)';");
    }
    catch(error_3){
        document.getElementById('errObj_prop-3').innerHTML =
            error_3 + "&lt;br&gt;" +
            error_3.name + "&lt;br&gt;" +
            error_3.message;
    }
// --- TypeError
    var Xstr = "thisText";
    try{
        Xstr.pop();
    }
    catch(error_4){
        document.getElementById('errObj_prop-4').innerHTML =
            error_4 + "&lt;br&gt;" +
            error_4.name + "&lt;br&gt;" +
            error_4.message;
    }
// --- URIError
    try{
        decodeURI("%£$*&");
    }
    catch(error_5){
        document.getElementById('errObj_prop-5').innerHTML =
            error_5 + "&lt;br&gt;" +
            error_5.name + "&lt;br&gt;" +
            error_5.message;
    }
&lt;/script&gt;
    </pre>
      </details>
      <h4><u> throwing custom errors </u></h4>
      <button onmouseup="throwError()"> Test (see console) </button>
      <script>
// any of these error objects or primitive datas can be thrown
    var error_obj = new Error("MY error");
    var error_range = RangeError("MY custom range error");
    var error_type = TypeError("MY custom type error");
    var error_syntax = SyntaxError("MY custom syntax error");
    var error_eval = EvalError("MY custom eval error");
    var error_reference = ReferenceError("MY custom reference error");
    var error_URI = URIError("MY custom reference error");
    
    var er_string = "myError";
    var er_nr = 24;
    var er_boolean = false;
// throw 
    function throwError(){
        throw error_range;                                  // error thrown and printed in console;
        throw er_nr;                                        // this would work but script is has stopped executing in the previous line
    
        console.warn("TEST SCRIPT IS RUNNING ----------");  // this and all further code isn't exectued 
    }
</script>
      <details>
        <summary> CODE : </summary>
        <pre>
    &lt;button onmouseup="throwError()"&gt; Test (see console) &lt;/button&gt;
&lt;script&gt;
// any of these error objects or primitive datas can be thrown
    var error_obj = new Error("MY error");
    var error_range = RangeError("MY custom range error");
    var error_type = TypeError("MY custom type error");
    var error_syntax = SyntaxError("MY custom syntax error");
    var error_eval = EvalError("MY custom eval error");
    var error_reference = ReferenceError("MY custom reference error");
    var error_URI = URIError("MY custom reference error");
    
    var er_string = "myError";
    var er_nr = 24;
    var er_boolean = false;
// throw 
    function throwError(){
        throw error_range;                                  // error thrown and printed in console;
        throw er_nr;                                        // this would work but script is has stopped executing in the previous line
    
        console.warn("TEST SCRIPT IS RUNNING ----------");  // this and all further code isn't exectued 
    }
&lt;/script&gt;
        </pre>
      </details>
    </details>
    <hr>
    <!--------------------------------------------------------------------------------------------------------------------------------->
    <h2 class="headerExtra"><u> The <mark>try...catch</mark> statement </u></h2>
    <p> - the <mark>try...catch</mark> statement is used try to run some code and cach eventual errors in a scope so the main program doesn't exit </p>
    <pre class="syntax">
    try {
        <i>// code to test...</i>
    }
    catch (<strong>err</strong>) {                  // code block executes if an error is thrown in the <mark>try</mark> block
                                                    // <span class="fab fa-js">2019</span> <span id="browserSupport" style="color:yellow;" title="updated : 2025-03-02"><span><i class="fab fa-chrome"></i> 65 </span><span><i class="fab fa-firefox"></i> 58 </span><span><i class="fab fa-opera"></i> 53 </span><span><i class="fab fa-internet-explorer"></i><i class="fab fa-edge"></i> 79 </span><span><i class="fab fa-safari"></i> 11.1 </span><span><i class="fab fa-node-js"></i> 10 </span></span>   // the <mark>(<strong>err</strong>)</mark> is optional
        <i>// error handling here... </i>
    }    
    finally {                                       // garanteed to executed regardless of the result of <mark>try</mark> and <mark>catch</mark> (even if the error is not handled) 
        <i>// finally code... </i> 
    }
    
    
// valid statemenet combinations ---------------------------
    <mark>try...catch</mark>
    <mark>try...finally</mark>
    <mark>try...catch...finally</mark>
    </pre>
    <details class="example">
      <summary> DEMO </summary>
      <pre>
    try {
        bla..bla                                                                       // this throws an error 
    }
    catch (err) {                                                                      // the error is caught and returned here 'err'   
        err;                                                                           // -> ReferenceError 
    }                                                                                  // the "catch" statement block only fires if error is thrown byt the "try" statement
    finally {
        console.log( "garanteed" );                                                    // block is garanteed to fire 
    }                                                                                  // if an error is thrown by the "try" statement and there is not "catch" statement to handle it all further code fails but the "finally" statemenet   
    
    console.log( 'continue' );                                                          // if the thrown error in not caught by the "catch" statement this won't be executed!    
    </pre>
    </details>
    <details class="example">
      <summary> Example : </summary>
      <h4><u> custom message throw</u></h4>
      <p> - enter a number between 5 and 10 </p>
      <input id="th-row-in" type="number">
      <button onclick="th_row()"> Test Input </button>
      <span id="th-row-out"> = </span>
      <script>
    function th_row(){
        var x = document.getElementById('th-row-in').value;
        try{
            if(x >= 5 && x <= 10) throw "Correct value entered";
            if(x > 10) throw "Entered value too High";
            if(x < 5) throw "Entered value too Low";
        }
        catch(err){
            document.getElementById('th-row-out').innerHTML = err;
        }
    }
</script>
      <details>
        <summary> CODE : </summary>
        <pre>
    &lt;p&gt; - enter a number between 5 and 10 &lt;/p&gt;
    &lt;input id="th-row-in" type="number"&gt;
    &lt;button onclick="th_row()"&gt; Test Input &lt;/button&gt;
    &lt;span id="th-row-out"&gt; = &lt;/span&gt;
&lt;script&gt;
    function th_row(){
        var x = document.getElementById('th-row-in').value;
        try{
            if(x &gt;= 5 && x &lt;= 10) throw "Correct value entered";
            if(x &gt; 10) throw "Entered value too High";
            if(x &lt; 5) throw "Entered value too Low";
        }
        catch(err){
            document.getElementById('th-row-out').innerHTML = err;
        }
    }
    </pre>
      </details>
      <!--------------------------------------------------------------------------------------------------------------------------------->
      <hr>
      <h4><u> finally statement fires all the time VS catch only if error occurs </u></h4>
      <p id="finally-out"></p>
      <script>
    var testNumber = 45;
    try{
        eval("testNumber.toFixed(10);");
    }
    catch(errorObj_1){                                                  // no error object generated
        var catchVAR_1 = "Error in the first test found";               // this hole statement is not fired because no error found
        document.write(errorObj_1);
    }
    finally{                                                            // this statement fires regardless of error found or not
        var finallyVAR_1 = "Finally_1 variable data";
    }
    
// --- error found here
    
    try{
        eval("testNumber.toFixed(123);");
    }
    catch(errorObj_2){                                                  // error object generated this time
        var catchVAR_2 = "Error in the second test found"               // statement executed because error found
        var eRRor = errorObj_2;                                         // the error is only displayable in the catch statement but you can transfer it as a variable
    }
    finally{
        var finallyVAR_2 = "Finally_2 variable data";                   // this statement fires regardless of error found or not
    }
    
    document.getElementById('finally-out').innerHTML = 
        " - 1) First test " + "<br>" +
        "Error Variable 1 = " + catchVAR_1 + "<br>" +
        "Finally Variable 1 = " + finallyVAR_1 + "<br>" +
        " - 2) Second test " + "<br>" +
        "Error Variable 2 = " + catchVAR_2 + "<br>" +
        "Finally Variable 2 = " + finallyVAR_2 + "<br>" +
        "Error Found = " + eRRor;
    
    //document.write(errorObj_2);                                       // this wouldn't work! (reported as a bug in the debugger window!)
    
</script>
      <details>
        <summary> CODE : </summary>
        <pre>
    &lt;p id="finally-out"&gt;&lt;/p&gt;
&lt;script&gt;
    var testNumber = 45;
    try{
        eval("testNumber.toFixed(10);");
    }
    catch(errorObj_1){                                                  // no error object generated
        var catchVAR_1 = "Error in the first test found";               // this hole statement is not fired because no error found
        document.write(errorObj_1);
    }
    finally{                                                            // this statement fires regardless of error found or not
        var finallyVAR_1 = "Finally_1 variable data";
    }
    
// --- error found here
    
    try{
        eval("testNumber.toFixed(123);");
    }
    catch(errorObj_2){                                                  // error object generated this time
        var catchVAR_2 = "Error in the second test found"               // statement executed because error found
        var eRRor = errorObj_2;                                         // the error is only displayable in the catch statement but you can transfer it as a variable
    }
    finally{
        var finallyVAR_2 = "Finally_2 variable data";                   // this statement fires regardless of error found or not
    }
    
    document.getElementById('finally-out').innerHTML = 
        " - 1) First test " + "&lt;br&gt;" +
        "Error Variable 1 = " + catchVAR_1 + "&lt;br&gt;" +
        "Finally Variable 1 = " + finallyVAR_1 + "&lt;br&gt;" +
        " - 2) Second test " + "&lt;br&gt;" +
        "Error Variable 2 = " + catchVAR_2 + "&lt;br&gt;" +
        "Finally Variable 2 = " + finallyVAR_2 + "&lt;br&gt;" +
        "Error Found = " + eRRor;
    
    document.write(errorObj_2);                                         // this won't work! (reported as a bug in the debugger window!)
    </pre>
      </details>
      <!--------------------------------------------------------------------------------------------------------------------------------->
      <hr>
      <h4><u> the <mark>finally</mark> statement real purpose test! </u></h4>
      <button onmouseup="finallyTest()"> Test (see console) </button>
      <script>
    function finallyTest(){
        try {
            ksdf                                            // this generates an "ReferenceError" but there is no catch statement to handle it
        }
        finally {
            console.log("finally statement test");          // this is GARANTEED to fired the "finally" statement doesn't give a FU.. it fires!
        }
        console.log("test statement after");                // since there is an error above this and all the code after will fail
    }
</script>
      <details>
        <summary> CODE : </summary>
        <pre>
    &lt;button onmouseup="finallyTest()"&gt; Test (see console) &lt;/button&gt;
&lt;script&gt;
    function finallyTest(){
        try {
            ksdf                                            // this generates an "ReferenceError" but there is no catch statement to handle it
        }
        finally {
            console.log("finally statement test");          // this is GARANTEED to fired the "finally" statement doesn't give a FU.. it fires!
        }
        console.log("test statement after");                // since there is an error above this and all the code after will fail
    }
&lt;/script&gt;  
        </pre>
      </details>
      <!--------------------------------------------------------------------------------------------------------------------------------->
      <hr>
      <h4 style="color:darkblue;"><u> catch Syntax Error TEST </u></h4>
      <p> - the <mark>try...catch</mark> statement cannot catch syntax errors </p>
      <pre>
    try{
        var 23wer                                                                      // Syntax Error thrown 
    } catch(err){                                                                      // any further code is not executed   
        console.log( err );                                         
    }
    
    console.log( 'code after try...catch statement' );
    </pre>
    </details>
    <!--------------------------------------------------------------------------------------------------------------------------------->
    <hr>
    <h2 class="headerExtra"><u> The <mark>throw</mark> and <mark>debugger</mark> statements </u></h2>
    <pre class="syntax">
                                                                                         <span id="browserSupport" style="color:yellow;" title="updated : 2021-06-05"><span><i class="fab fa-chrome"></i> 1 </span><span><i class="fab fa-firefox"></i> 1 </span><span><i class="fab fa-opera"></i> 4 </span><span><i class="fab fa-internet-explorer"></i><i class="fab fa-edge"></i> 5 </span><span><i class="fab fa-safari"></i> 1 </span><span><i class="fab fa-node-js"></i> 0.10.0 </span></span>    
SYNTAX :    throw <strong>exp</strong>                                                                  // throws an exception and stops all further script execution (unwinds the stack / raises an exception)     
            
                                                                                         <span id="browserSupport" style="color:yellow;" title="updated : 2021-06-05"><span><i class="fab fa-chrome"></i> 5 </span><span><i class="fab fa-firefox"></i> 1 </span><span><i class="fab fa-opera"></i> 10 </span><span><i class="fab fa-internet-explorer"></i><i class="fab fa-edge"></i> 4 </span><span><i class="fab fa-safari"></i> 5 </span><span><i class="fab fa-node-js"></i> 0.10.0 </span></span>    
            debugger                                                                   // invokes the debugging functionality of the host (if any)    
                                                                                          if the host has a debugger the code is handled accordingly (ex: in the browser sets a breakpoint and opens the console window)   
                                                                                          if the host doesn't have any debugger this statement does nothing     
    </pre>
    <details class="example">
      <summary> DEMO </summary>
      <pre>
    var myCustom_error = new Error("my error message");
    throw myCustom_error;                                                              // (error object) throws exception "my error message" message printen in console
    throw "myError";                                                                   // (string) throws exception "myError" message printed in console
        // some code...                                                                // -! code not executed after the "throw" statement
    
// Unwinding the Stack -----------------
    function myFunc_A() { return myFunc_B()};
    function myFunc_B() { return myFunc_C()};
    function myFunc_C() { return myFunc_D()};
    function myFunc_D() {
        throw "I'm Raised!";                                                           // exception throwed directly to the caller "myFunc_A()"  -->  "unwinds the stack"
    }                                                                                  // "myFunc_B()" and "myFunc_C()" are ignored at this point 
    
    myFunc_A();                                                                        // exception is throwed here
    </pre>
      <pre>
    var myDocument = document;
    debugger;                                                                          // debugger functionality of the browser called here (script paused)
    console.info(typeof myDocument);                                                   // -! not executed 
    </pre>
    </details>
    <details class="example">
      <summary> Example : </summary>
      <h4><u> unwinding the stack / raising an exeption </u></h4>
      <p id="raiseUp"></p>
      <script>
"use strict";
    try {
        document.getElementById('raiseUp').innerHTML = func_A("asdf");
    }
    catch (err) {
        document.getElementById('raiseUp').innerHTML = err;
    }
    
    function func_A(bol) {
        return func_B(bol);
    }
    function func_B(bol) {
        return func_C(bol);
    }
    function func_C(bol) {
        if (bol == "true") return "Value is \"true\"";
        else if (bol == "false") return "Value is \"false\"";
        else {
            throw Error("Not a boolean value!");            // returns directly to "func_A()" (caller) and ignores entierly "func_B()"
        }                                                   // it does not even need any "return" statement!
    }
</script>
      <details>
        <summary> CODE : </summary>
        <pre>
    &lt;p id="raiseUp"&gt;&lt;/p&gt;
&lt;script&gt;
"use strict";
    try {
        document.getElementById('raiseUp').innerHTML = func_A("asdf");
    }
    catch (err) {
        document.getElementById('raiseUp').innerHTML = err;
    }
    
    function func_A(bol) {
        return func_B(bol);
    }
    function func_B(bol) {
        return func_C(bol);
    }
    function func_C(bol) {
        if (bol == "true") return "Value is \"true\"";
        else if (bol == "false") return "Value is \"false\"";
        else {
            throw Error("Not a boolean value!");            // returns directly to "func_A()" (caller) and ignores entierly "func_B()"
        }                                                   // it does not even need any "return" statement!
    }
&lt;/script&gt;
        </pre>
      </details>
      <!--------------------------------------------------------------------------------------------------------------------------------->
      <hr>
      <h4><u> <mark>debugger</mark> statement TEST </u> </h4>
      <p> - open the console window and active the debugger code with the below button to see the effect <u>(effect remains until tab closed!)</u> </p>
      <button onmouseup="activeDebug()"> Activate debugger </button>
      <p id="debug" style="font-weight:bold; color:red;"></p>
      <script>
    function activeDebug() {
        var A = 5;
        var B = 5;
        debugger;                                       // debugger funtionality fired when invoked
        var C = A + B;
        document.getElementById('debug').innerHTML = C;
    }
</script>
      <details>
        <summary> CODE : </summary>
        <pre>
    &lt;button onmouseup="activeDebug()"&gt; Activate debugger &lt;/button&gt;
    &lt;p id="debug" style="font-weight:bold; color:red;"&gt;&lt;/p&gt;
&lt;script&gt;
    function activeDebug() {
        var A = 5;
        var B = 5;
        debugger;                                       // debugger funtionality fired when invoked
        var C = A + B;
        document.getElementById('debug').innerHTML = C;
    }
&lt;/script&gt;
        </pre>
      </details>
    </details>

    <br><br>
  </body>
</html>